version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-npm:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-npm:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    exclude-paths:
      - requirements-ci.txt
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
