/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerIndexRouteImport } from './routes/viewer.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as ViewerImageIdRouteImport } from './routes/viewer.$imageId'
import { Route as LibraryRunIdRouteImport } from './routes/library.$runId'

const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerIndexRoute = ViewerIndexRouteImport.update({
  id: '/viewer/',
  path: '/viewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const ViewerImageIdRoute = ViewerImageIdRouteImport.update({
  id: '/viewer/$imageId',
  path: '/viewer/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRunIdRoute = LibraryRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/generate': typeof GenerateRoute
  '/health': typeof HealthRoute
  '/library': typeof LibraryRouteWithChildren
  '/registry': typeof RegistryRoute
  '/spend': typeof SpendRoute
  '/library/$runId': typeof LibraryRunIdRoute
  '/viewer/$imageId': typeof ViewerImageIdRoute
  '/library/': typeof LibraryIndexRoute
  '/viewer/': typeof ViewerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/generate': typeof GenerateRoute
  '/health': typeof HealthRoute
  '/registry': typeof RegistryRoute
  '/spend': typeof SpendRoute
  '/library/$runId': typeof LibraryRunIdRoute
  '/viewer/$imageId': typeof ViewerImageIdRoute
  '/library': typeof LibraryIndexRoute
  '/viewer': typeof ViewerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/generate': typeof GenerateRoute
  '/health': typeof HealthRoute
  '/library': typeof LibraryRouteWithChildren
  '/registry': typeof RegistryRoute
  '/spend': typeof SpendRoute
  '/library/$runId': typeof LibraryRunIdRoute
  '/viewer/$imageId': typeof ViewerImageIdRoute
  '/library/': typeof LibraryIndexRoute
  '/viewer/': typeof ViewerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/generate'
    | '/health'
    | '/library'
    | '/registry'
    | '/spend'
    | '/library/$runId'
    | '/viewer/$imageId'
    | '/library/'
    | '/viewer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/generate'
    | '/health'
    | '/registry'
    | '/spend'
    | '/library/$runId'
    | '/viewer/$imageId'
    | '/library'
    | '/viewer'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/generate'
    | '/health'
    | '/library'
    | '/registry'
    | '/spend'
    | '/library/$runId'
    | '/viewer/$imageId'
    | '/library/'
    | '/viewer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRoute
  GenerateRoute: typeof GenerateRoute
  HealthRoute: typeof HealthRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  RegistryRoute: typeof RegistryRoute
  SpendRoute: typeof SpendRoute
  ViewerImageIdRoute: typeof ViewerImageIdRoute
  ViewerIndexRoute: typeof ViewerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/': {
      id: '/viewer/'
      path: '/viewer'
      fullPath: '/viewer/'
      preLoaderRoute: typeof ViewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/viewer/$imageId': {
      id: '/viewer/$imageId'
      path: '/viewer/$imageId'
      fullPath: '/viewer/$imageId'
      preLoaderRoute: typeof ViewerImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$runId': {
      id: '/library/$runId'
      path: '/$runId'
      fullPath: '/library/$runId'
      preLoaderRoute: typeof LibraryRunIdRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryRunIdRoute: typeof LibraryRunIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryRunIdRoute: LibraryRunIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRoute,
  GenerateRoute: GenerateRoute,
  HealthRoute: HealthRoute,
  LibraryRoute: LibraryRouteWithChildren,
  RegistryRoute: RegistryRoute,
  SpendRoute: SpendRoute,
  ViewerImageIdRoute: ViewerImageIdRoute,
  ViewerIndexRoute: ViewerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
