from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path


def generate_viewer(
    output_dir: Path,
    items: list[dict],
    title: str = "Rafiki — Image Batch",
    run_meta: dict | None = None,
) -> Path:
    """Generate a single-run HTML viewer alongside the batch output images."""
    output_dir = Path(output_dir)
    meta = run_meta or {}

    timestamp = meta.get("timestamp", datetime.now().strftime("%Y-%m-%d %H:%M"))
    model = meta.get("model", "—")
    aspect_ratio = meta.get("aspect_ratio", "—")
    style = meta.get("style", "—")
    prompt_file = meta.get("prompt_file", "")

    js_items = []
    for item in items:
        out = Path(item.get("output_path", ""))
        try:
            rel = str(out.relative_to(output_dir))
        except ValueError:
            rel = out.name
        js_items.append({
            "name": item.get("name", "Untitled"),
            "prompt": item.get("prompt", ""),
            "file": rel,
            "ok": out.exists(),
        })

    html = _render_single(title, js_items, model, aspect_ratio, style, timestamp, prompt_file)
    viewer_path = output_dir / "viewer.html"
    viewer_path.write_text(html, encoding="utf-8")
    return viewer_path


def generate_comparison_viewer(project_dir: Path) -> Path:
    """Scan all run-* subdirs and generate a multi-run comparison viewer."""
    project_dir = Path(project_dir)

    run_json_paths = sorted(project_dir.glob("run-*/run.json"))
    runs = []
    for rjp in run_json_paths:
        try:
            data = json.loads(rjp.read_text(encoding="utf-8"))
            runs.append({
                "id": rjp.parent.name,
                "dir": rjp.parent.name,
                "timestamp": data.get("timestamp", ""),
                "model": data.get("model", ""),
                "style": data.get("style", "none"),
                "aspect_ratio": data.get("aspect_ratio", ""),
                "prompt_file": data.get("prompt_file", ""),
                "images": data.get("images", []),
            })
        except Exception:
            continue

    title = project_dir.name.replace("-", " ").replace("_", " ").title()
    html = _render_comparison(title, runs)
    viewer_path = project_dir / "viewer.html"
    viewer_path.write_text(html, encoding="utf-8")
    return viewer_path


# ─── Single-run renderer ─────────────────────────────────────────────────────

def _render_single(
    title: str,
    items: list[dict],
    model: str,
    aspect_ratio: str,
    style: str,
    timestamp: str,
    prompt_file: str,
) -> str:
    items_json = json.dumps(items, ensure_ascii=False)
    count = len(items)
    source_line = f"Source: <code>{prompt_file}</code> · " if prompt_file else ""

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
{_shared_css()}
</head>
<body>
<header>
  <h1>{title}</h1>
  <div class="meta">
    <span class="pill">{count} image{'' if count == 1 else 's'}</span>
    <span>Model: <code>{model}</code></span>
    <span>Ratio: <code>{aspect_ratio}</code></span>
    <span>Style: <code>{style}</code></span>
    <span>{source_line}Generated {timestamp}</span>
  </div>
</header>

{_filter_bar_html()}
<div class="grid" id="grid"></div>

{_lightbox_html()}

<footer>
  Generated by <code>rafiki</code> · {timestamp}
</footer>

<script>
const ITEMS = {items_json};
{_rating_js()}
{_grid_js()}
{_lightbox_js()}
</script>
</body>
</html>"""


# ─── Comparison renderer ──────────────────────────────────────────────────────

def _render_comparison(title: str, runs: list[dict]) -> str:
    runs_json = json.dumps(runs, ensure_ascii=False)
    run_count = len(runs)

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} — Rafiki Comparison</title>
{_shared_css()}
<style>
/* ── Run tabs ── */
.run-tabs {{
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem;
  padding: 0.75rem 2rem;
  border-bottom: 1px solid var(--border);
  background: rgba(0,0,0,0.2);
  align-items: center;
}}
.run-tab {{
  background: var(--surface);
  border: 1px solid var(--border);
  color: var(--dim);
  padding: 0.3rem 0.8rem;
  border-radius: 20px;
  font-size: 0.78rem;
  cursor: pointer;
  transition: all 0.15s;
  user-select: none;
  white-space: nowrap;
}}
.run-tab:hover {{ border-color: var(--accent); color: var(--ink); }}
.run-tab.active {{ background: rgba(124,106,247,0.2); border-color: var(--accent); color: var(--accent); font-weight: 600; }}
.run-tab.compare-btn {{
  margin-left: auto;
  background: rgba(0,200,180,0.1);
  border-color: rgba(0,200,180,0.4);
  color: var(--accent2);
}}
.run-tab.compare-btn.active {{
  background: rgba(0,200,180,0.25);
  border-color: var(--accent2);
}}
.run-count {{
  font-size: 0.72rem;
  color: var(--dim);
  padding: 0 0.25rem;
}}

/* ── Compare grid (rows = prompts, cols = runs) ── */
.compare-table {{
  display: none;
  padding: 1.5rem 2rem 3rem;
  overflow-x: auto;
}}
.compare-table.visible {{ display: block; }}
.compare-row {{
  display: grid;
  gap: 0.75rem;
  margin-bottom: 1.5rem;
  align-items: start;
}}
.compare-label {{
  font-size: 0.82rem;
  font-weight: 600;
  color: var(--ink);
  padding: 0.5rem 0 0.25rem;
  border-bottom: 1px solid var(--border);
  margin-bottom: 0.5rem;
  grid-column: 1 / -1;
}}
.compare-cell {{
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  overflow: hidden;
  cursor: pointer;
  transition: border-color 0.15s, transform 0.15s;
}}
.compare-cell:hover {{ border-color: var(--accent); transform: translateY(-2px); }}
.compare-cell .run-label {{
  font-size: 0.68rem;
  color: var(--accent);
  padding: 0.3rem 0.5rem;
  font-weight: 600;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}}
.compare-cell .run-ts {{
  font-size: 0.65rem;
  color: var(--dim);
  padding: 0 0.5rem 0.4rem;
}}
.no-runs {{
  padding: 4rem 2rem;
  text-align: center;
  color: var(--dim);
  font-size: 0.9rem;
}}
</style>
</head>
<body>

<header>
  <h1>{title}</h1>
  <div class="meta">
    <span class="pill" id="run-summary">{run_count} run{'' if run_count == 1 else 's'}</span>
    <span id="cur-model"></span>
    <span id="cur-ts"></span>
  </div>
</header>

<div class="run-tabs" id="run-tabs">
  <span class="run-count" id="run-count-label">{run_count} run{'' if run_count == 1 else 's'}</span>
  <button class="run-tab compare-btn" id="compare-btn" onclick="toggleCompare()">⊞ Compare all</button>
</div>

{_filter_bar_html()}
<div class="grid" id="grid"></div>
<div class="compare-table" id="compare-table"></div>

{_lightbox_html()}

<footer id="footer">
  Generated by <code>rafiki</code>
</footer>

<script>
const RUNS = {runs_json};
let currentRun = RUNS.length - 1;
let compareMode = false;

{_rating_js()}
{_comparison_js()}
{_lightbox_js()}
</script>
</body>
</html>"""


# ─── Shared HTML/CSS/JS fragments ────────────────────────────────────────────

def _shared_css() -> str:
    return """<style>
:root {
  --bg:      #0f0c1a;
  --bg2:     #1a1530;
  --surface: rgba(255,255,255,0.04);
  --border:  #2d2550;
  --ink:     #ede9ff;
  --dim:     #9f9abd;
  --accent:  #7c6af7;
  --accent2: #00c8b4;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: linear-gradient(160deg, var(--bg) 0%, var(--bg2) 100%);
  color: var(--ink);
  font-family: ui-sans-serif, system-ui, -apple-system, "Helvetica Neue", sans-serif;
  line-height: 1.5;
  min-height: 100vh;
}

/* ── Header ── */
header {
  padding: 2rem 2rem 1.25rem;
  border-bottom: 1px solid var(--border);
}
header h1 {
  font-size: 1.6rem;
  letter-spacing: -0.02em;
  margin-bottom: 0.4rem;
  background: linear-gradient(90deg, var(--accent), var(--accent2));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
.meta {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem 1.5rem;
  font-size: 0.85rem;
  color: var(--dim);
  margin-top: 0.25rem;
}
.meta code {
  background: rgba(255,255,255,0.07);
  padding: 0.1rem 0.4rem;
  border-radius: 4px;
  font-size: 0.8rem;
  color: var(--accent2);
}
.meta .pill {
  background: rgba(124,106,247,0.15);
  border: 1px solid rgba(124,106,247,0.3);
  color: var(--accent);
  padding: 0.15rem 0.55rem;
  border-radius: 20px;
  font-size: 0.78rem;
  font-weight: 600;
  letter-spacing: 0.01em;
}

/* ── Filter bar ── */
.filter-bar {
  display: flex;
  gap: 0.4rem;
  padding: 0.75rem 2rem 0;
  flex-wrap: wrap;
  align-items: center;
}
.filter-btn {
  background: var(--surface);
  border: 1px solid var(--border);
  color: var(--dim);
  padding: 0.28rem 0.75rem;
  border-radius: 20px;
  font-size: 0.78rem;
  cursor: pointer;
  transition: all 0.15s;
  user-select: none;
}
.filter-btn:hover { border-color: var(--accent); color: var(--ink); }
.filter-btn.active { background: rgba(124,106,247,0.2); border-color: var(--accent); color: var(--accent); font-weight: 600; }

/* ── Grid ── */
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 1.1rem;
  padding: 1rem 2rem 3rem;
}

/* ── Card ── */
.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  overflow: hidden;
  cursor: pointer;
  transition: transform 0.15s ease, border-color 0.15s ease, box-shadow 0.15s ease;
}
.card:hover {
  transform: translateY(-3px);
  border-color: var(--accent);
  box-shadow: 0 8px 30px rgba(124,106,247,0.18);
}
.card.rated-star   { border-color: gold !important; box-shadow: 0 0 18px rgba(255,200,0,0.25); }
.card.rated-reject { opacity: 0.45; }
.card.hidden-filter { display: none; }

/* fixed height, no crop — all image shapes sit properly */
.img-wrap {
  height: 190px;
  background: #0a0814;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}
.img-wrap img {
  width: 100%;
  height: 100%;
  object-fit: contain;
  display: block;
}
.missing {
  color: var(--dim);
  font-size: 0.8rem;
  text-align: center;
  padding: 1.5rem;
  opacity: 0.6;
}
.card-body { padding: 0.75rem 0.9rem 0.5rem; }
.card-name {
  font-size: 0.92rem;
  font-weight: 600;
  color: var(--ink);
  margin-bottom: 0.3rem;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.card-num {
  font-size: 0.72rem;
  color: var(--accent);
  font-weight: 700;
  margin-right: 0.35rem;
  font-variant-numeric: tabular-nums;
}
.card-prompt {
  font-size: 0.78rem;
  color: var(--dim);
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.card-file {
  margin-top: 0.4rem;
  font-size: 0.72rem;
  color: rgba(255,255,255,0.2);
  font-family: ui-monospace, monospace;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

/* ── Rating bar ── */
.card-rating {
  display: flex;
  gap: 0.4rem;
  padding: 0.45rem 0.9rem 0.6rem;
  border-top: 1px solid var(--border);
}
.btn-rate {
  background: none;
  border: 1px solid rgba(255,255,255,0.1);
  color: var(--dim);
  font-size: 0.8rem;
  padding: 0.18rem 0.55rem;
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.15s;
  line-height: 1.4;
}
.btn-rate:hover { border-color: rgba(255,255,255,0.3); color: var(--ink); }
.btn-rate.starred  { background: rgba(255,200,0,0.15); border-color: gold; color: gold; }
.btn-rate.rejected { background: rgba(255,60,60,0.1); border-color: rgba(255,60,60,0.4); color: #ff6060; }

/* ── Lightbox ── */
.lb {
  display: none;
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.94);
  z-index: 1000;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  flex-direction: column;
  gap: 1rem;
}
.lb.open { display: flex; }
.lb-img-wrap {
  position: relative;
  max-width: min(92vw, 1400px);
  max-height: 80vh;
  display: flex;
  align-items: center;
  justify-content: center;
}
.lb img {
  max-width: 100%;
  max-height: 80vh;
  object-fit: contain;
  border-radius: 6px;
  box-shadow: 0 20px 70px rgba(0,0,0,0.7);
  display: block;
}
.lb-nav {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  background: rgba(255,255,255,0.1);
  border: 1px solid rgba(255,255,255,0.15);
  color: #fff;
  font-size: 1.4rem;
  line-height: 1;
  width: 2.6rem;
  height: 2.6rem;
  border-radius: 50%;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.15s;
  user-select: none;
}
.lb-nav:hover { background: rgba(255,255,255,0.2); }
.lb-nav.prev { left: -3.5rem; }
.lb-nav.next { right: -3.5rem; }
.lb-caption {
  text-align: center;
  max-width: 700px;
}
.lb-caption .name {
  font-size: 1rem;
  font-weight: 600;
  color: var(--ink);
  margin-bottom: 0.25rem;
}
.lb-caption .prompt {
  font-size: 0.82rem;
  color: var(--dim);
  line-height: 1.5;
}
.lb-close {
  position: fixed;
  top: 1.2rem;
  right: 1.5rem;
  background: rgba(255,255,255,0.1);
  border: none;
  color: #fff;
  font-size: 1.5rem;
  line-height: 1;
  width: 2.4rem;
  height: 2.4rem;
  border-radius: 50%;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}
.lb-close:hover { background: rgba(255,255,255,0.2); }

/* ── Run strip (lightbox, compare mode) ── */
.lb-run-strip {
  display: flex;
  gap: 0.4rem;
  flex-wrap: wrap;
  justify-content: center;
  max-width: 700px;
}
.lb-run-dot {
  background: rgba(255,255,255,0.1);
  border: 1px solid rgba(255,255,255,0.15);
  color: var(--dim);
  padding: 0.2rem 0.55rem;
  border-radius: 12px;
  font-size: 0.72rem;
  cursor: pointer;
  transition: all 0.12s;
  white-space: nowrap;
}
.lb-run-dot:hover { border-color: var(--accent2); color: var(--accent2); }
.lb-run-dot.active { background: rgba(0,200,180,0.2); border-color: var(--accent2); color: var(--accent2); font-weight: 600; }

/* ── Footer ── */
footer {
  padding: 1.5rem 2rem;
  border-top: 1px solid var(--border);
  text-align: center;
  color: var(--dim);
  font-size: 0.82rem;
}
footer code { color: var(--accent2); }
</style>"""


def _filter_bar_html() -> str:
    return """<div class="filter-bar" id="filter-bar">
  <button class="filter-btn active" id="fb-all"        onclick="filterCards('all')">All <span id="fc-all"></span></button>
  <button class="filter-btn"        id="fb-star"       onclick="filterCards('star')">★ Starred <span id="fc-star"></span></button>
  <button class="filter-btn"        id="fb-reject"     onclick="filterCards('reject')">✕ Rejected <span id="fc-reject"></span></button>
  <button class="filter-btn"        id="fb-unreviewed" onclick="filterCards('unreviewed')">Unreviewed <span id="fc-unreviewed"></span></button>
</div>"""


def _lightbox_html() -> str:
    return """<div class="lb" id="lb" onclick="lbClickBg(event)">
  <button class="lb-close" onclick="lbClose()" title="Close (Esc)">✕</button>
  <div class="lb-img-wrap">
    <button class="lb-nav prev" onclick="lbStep(-1); event.stopPropagation()">&#8592;</button>
    <img id="lb-img" src="" alt="">
    <button class="lb-nav next" onclick="lbStep(1); event.stopPropagation()">&#8594;</button>
  </div>
  <div class="lb-caption">
    <div class="name" id="lb-name"></div>
    <div class="prompt" id="lb-prompt"></div>
  </div>
  <div class="lb-run-strip" id="lb-run-strip"></div>
</div>"""


def _rating_js() -> str:
    return """
// ── Ratings (localStorage) ──────────────────────────────────────────────────
const RATINGS_KEY = 'rafiki:ratings';
let _currentFilter = 'all';

function _loadRatings() {
  try { return JSON.parse(localStorage.getItem(RATINGS_KEY) || '{}'); } catch(e) { return {}; }
}
function _saveRatings(r) { localStorage.setItem(RATINGS_KEY, JSON.stringify(r)); }
function getRating(key) { return _loadRatings()[key] || null; }
function setRating(key, val) {
  const r = _loadRatings();
  if (r[key] === val) delete r[key]; else r[key] = val;
  _saveRatings(r);
}
function applyRating(card, key) {
  const val = getRating(key);
  card.classList.remove('rated-star', 'rated-reject');
  if (val === 'star')   card.classList.add('rated-star');
  if (val === 'reject') card.classList.add('rated-reject');
  const btnS = card.querySelector('.btn-rate.star');
  const btnR = card.querySelector('.btn-rate.reject');
  if (btnS) btnS.classList.toggle('starred',  val === 'star');
  if (btnR) btnR.classList.toggle('rejected', val === 'reject');
}
function rateCard(e, key, val, card) {
  e.stopPropagation();
  setRating(key, val);
  applyRating(card, key);
  updateFilterCounts();
  if (_currentFilter !== 'all') filterCards(_currentFilter);
}
function filterCards(mode) {
  _currentFilter = mode;
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  const active = document.getElementById('fb-' + mode);
  if (active) active.classList.add('active');
  const ratings = _loadRatings();
  document.querySelectorAll('.card').forEach(card => {
    const val = ratings[card.dataset.ratingKey] || null;
    let show = true;
    if (mode === 'star')            show = val === 'star';
    else if (mode === 'reject')     show = val === 'reject';
    else if (mode === 'unreviewed') show = !val;
    card.classList.toggle('hidden-filter', !show);
  });
}
function updateFilterCounts() {
  const ratings = _loadRatings();
  const cards = Array.from(document.querySelectorAll('.card'));
  let stars = 0, rejects = 0, unreviewed = 0;
  cards.forEach(c => {
    const v = ratings[c.dataset.ratingKey] || null;
    if (v === 'star') stars++; else if (v === 'reject') rejects++; else unreviewed++;
  });
  const set = (id, n) => { const el = document.getElementById(id); if (el) el.textContent = n; };
  set('fc-all', cards.length); set('fc-star', stars);
  set('fc-reject', rejects);   set('fc-unreviewed', unreviewed);
}
"""


def _grid_js() -> str:
    return """
// Build grid
const grid = document.getElementById('grid');
ITEMS.forEach((item, i) => {
  const card = document.createElement('div');
  card.className = 'card';
  card.dataset.ratingKey = item.file;
  card.onclick = () => lbOpen(i);

  const promptShort = item.prompt.length > 140
    ? item.prompt.slice(0, 140) + '…'
    : item.prompt;
  const rk = item.file;

  card.innerHTML = `
    <div class="img-wrap">
      ${item.ok
        ? `<img src="${item.file}" alt="${item.name}" loading="lazy">`
        : `<div class="missing">Not generated yet</div>`
      }
    </div>
    <div class="card-body">
      <div class="card-name">
        <span class="card-num">${String(i + 1).padStart(2, '0')}</span>${item.name}
      </div>
      <div class="card-prompt" title="${item.prompt.replace(/"/g, '&quot;')}">${promptShort}</div>
      <div class="card-file">${item.file}</div>
    </div>
    <div class="card-rating">
      <button class="btn-rate star"   onclick="rateCard(event,'${rk}','star',  this.closest('.card'))">★ Star</button>
      <button class="btn-rate reject" onclick="rateCard(event,'${rk}','reject',this.closest('.card'))">✕ Reject</button>
    </div>
  `;
  grid.appendChild(card);
  applyRating(card, rk);
});
updateFilterCounts();
"""


def _lightbox_js() -> str:
    return """
// Lightbox (shared)
let lbIdx = 0;
let lbItems = typeof ITEMS !== 'undefined' ? ITEMS : [];
let lbRunIdx = -1;  // -1 = no run context (single-run viewer)
const lb       = document.getElementById('lb');
const lbImg    = document.getElementById('lb-img');
const lbName   = document.getElementById('lb-name');
const lbPrompt = document.getElementById('lb-prompt');
const lbStrip  = document.getElementById('lb-run-strip');

function lbOpen(i, runIdx) {
  if (typeof runIdx !== 'undefined') lbRunIdx = runIdx;
  lbIdx = ((i % lbItems.length) + lbItems.length) % lbItems.length;
  const item = lbItems[lbIdx];
  const prefix = (lbRunIdx >= 0 && typeof RUNS !== 'undefined')
    ? RUNS[lbRunIdx].dir + '/'
    : '';
  lbImg.src = prefix + item.file;
  lbName.textContent = item.name;
  lbPrompt.textContent = item.prompt.length > 300
    ? item.prompt.slice(0, 300) + '…'
    : item.prompt;
  _buildRunStrip(lbIdx);
  lb.classList.add('open');
}

function _buildRunStrip(slotIdx) {
  if (!lbStrip) return;
  lbStrip.innerHTML = '';
  if (typeof RUNS === 'undefined' || RUNS.length <= 1) return;
  RUNS.forEach((run, ri) => {
    const dot = document.createElement('button');
    dot.className = 'lb-run-dot' + (ri === lbRunIdx ? ' active' : '');
    dot.textContent = run.timestamp || run.id;
    dot.onclick = (e) => {
      e.stopPropagation();
      lbRunIdx = ri;
      lbItems = run.images;
      lbOpen(slotIdx, ri);
    };
    lbStrip.appendChild(dot);
  });
}

function lbClose() { lb.classList.remove('open'); }
function lbStep(dir) { lbOpen(lbIdx + dir); event.stopPropagation(); }
function lbClickBg(e) { if (e.target === lb) lbClose(); }

document.addEventListener('keydown', e => {
  if (!lb.classList.contains('open')) return;
  if (e.key === 'Escape')      lbClose();
  if (e.key === 'ArrowLeft')   lbOpen(lbIdx - 1);
  if (e.key === 'ArrowRight')  lbOpen(lbIdx + 1);
});
"""


def _comparison_js() -> str:
    return """
function init() {
  if (!RUNS.length) {
    document.getElementById('grid').innerHTML =
      '<div class="no-runs">No runs found.</div>';
    return;
  }

  // Build run tabs
  const tabsEl = document.getElementById('run-tabs');
  const compareBtn = document.getElementById('compare-btn');

  RUNS.forEach((run, ri) => {
    const tab = document.createElement('button');
    tab.className = 'run-tab' + (ri === currentRun ? ' active' : '');
    tab.textContent = `Run ${ri + 1}  ${run.timestamp}`;
    tab.title = `${run.dir}  ·  ${run.model}  ·  style: ${run.style}`;
    tab.onclick = () => switchRun(ri);
    tabsEl.insertBefore(tab, compareBtn);
  });

  showRun(currentRun);
}

function switchRun(ri) {
  compareMode = false;
  currentRun = ri;
  document.querySelectorAll('.run-tab:not(.compare-btn)').forEach((t, i) => {
    t.classList.toggle('active', i === ri);
  });
  document.getElementById('compare-btn').classList.remove('active');
  document.getElementById('compare-table').classList.remove('visible');
  const filterBar = document.getElementById('filter-bar');
  if (filterBar) filterBar.style.display = 'flex';
  showRun(ri);
}

function showRun(ri) {
  const run = RUNS[ri];
  lbItems = run.images;
  lbRunIdx = ri;

  document.getElementById('cur-model').innerHTML =
    run.model ? `Model: <code>${run.model}</code>` : '';
  document.getElementById('cur-ts').textContent =
    run.timestamp ? `Generated ${run.timestamp}` : '';
  document.getElementById('footer').innerHTML =
    `Generated by <code>rafiki</code> · ${run.timestamp || ''} · ${run.dir}`;

  const grid = document.getElementById('grid');
  grid.style.display = 'grid';
  grid.innerHTML = '';

  run.images.forEach((item, i) => {
    const card = document.createElement('div');
    card.className = 'card';
    const rk = run.dir + '/' + item.file;
    card.dataset.ratingKey = rk;
    card.onclick = () => lbOpen(i, ri);

    const promptShort = item.prompt.length > 140
      ? item.prompt.slice(0, 140) + '…'
      : item.prompt;

    card.innerHTML = `
      <div class="img-wrap">
        ${item.ok
          ? `<img src="${run.dir}/${item.file}" alt="${item.name}" loading="lazy">`
          : `<div class="missing">Not generated yet</div>`
        }
      </div>
      <div class="card-body">
        <div class="card-name">
          <span class="card-num">${String(i + 1).padStart(2, '0')}</span>${item.name}
        </div>
        <div class="card-prompt" title="${item.prompt.replace(/"/g, '&quot;')}">${promptShort}</div>
        <div class="card-file">${run.dir}/${item.file}</div>
      </div>
      <div class="card-rating">
        <button class="btn-rate star"   onclick="rateCard(event,'${rk}','star',  this.closest('.card'))">&#9733; Star</button>
        <button class="btn-rate reject" onclick="rateCard(event,'${rk}','reject',this.closest('.card'))">&#10005; Reject</button>
      </div>
    `;
    grid.appendChild(card);
    applyRating(card, rk);
  });
  updateFilterCounts();
}

function toggleCompare() {
  compareMode = !compareMode;
  document.getElementById('compare-btn').classList.toggle('active', compareMode);
  document.getElementById('grid').style.display = compareMode ? 'none' : 'grid';
  const filterBar = document.getElementById('filter-bar');
  if (filterBar) filterBar.style.display = compareMode ? 'none' : 'flex';
  const ct = document.getElementById('compare-table');
  ct.classList.toggle('visible', compareMode);
  if (compareMode) buildCompareTable();
}

function buildCompareTable() {
  const ct = document.getElementById('compare-table');
  ct.innerHTML = '';

  if (!RUNS.length) return;
  const slotCount = Math.max(...RUNS.map(r => r.images.length));
  const colCount = RUNS.length;

  for (let si = 0; si < slotCount; si++) {
    const firstSlot = RUNS.find(r => r.images[si]);
    if (!firstSlot) continue;
    const slotName = firstSlot.images[si]?.name || `Slot ${si + 1}`;
    const slotPrompt = firstSlot.images[si]?.prompt || '';

    // Label row
    const label = document.createElement('div');
    label.className = 'compare-label';
    label.textContent = `${String(si + 1).padStart(2, '0')} — ${slotName}`;
    label.title = slotPrompt;
    ct.appendChild(label);

    // Image row
    const row = document.createElement('div');
    row.className = 'compare-row';
    row.style.gridTemplateColumns = `repeat(${colCount}, minmax(200px, 1fr))`;
    ct.appendChild(row);

    RUNS.forEach((run, ri) => {
      const img = run.images[si];
      const cell = document.createElement('div');
      cell.className = 'compare-cell';
      if (img) cell.onclick = () => { lbItems = run.images; lbOpen(si, ri); };

      cell.innerHTML = `
        <div class="img-wrap" style="height:140px">
          ${img && img.ok
            ? `<img src="${run.dir}/${img.file}" alt="${img.name}" loading="lazy">`
            : `<div class="missing">${img ? 'Failed' : 'No image'}</div>`
          }
        </div>
        <div class="run-label">Run ${ri + 1}</div>
        <div class="run-ts">${run.timestamp}</div>
      `;
      row.appendChild(cell);
    });
  }
}

init();
"""
